spring:
  application:
    name: MoneyManagerBackClient
  datasource:
    url: jdbc:postgresql://localhost:5432/MoneyManagerBaseClient
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
